<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerScqsUcx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerScqsUcx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerScqsUcx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerScqsUcx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerScqsUcx\App_KernelDevDebugContainer([
    'container.build_hash' => 'ScqsUcx',
    'container.build_id' => '4fc0f4b6',
    'container.build_time' => 1650900280,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerScqsUcx');
