<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'main_page' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/']], [], []],
    'pizzaList' => [[], ['_controller' => 'App\\Controller\\ProductController::pizzaList'], [], [['text', '/pizzas']], [], []],
    'drinkList' => [[], ['_controller' => 'App\\Controller\\ProductController::drinkList'], [], [['text', '/drinks']], [], []],
    'rollList' => [[], ['_controller' => 'App\\Controller\\ProductController::rollList'], [], [['text', '/rolls']], [], []],
    'kitList' => [[], ['_controller' => 'App\\Controller\\ProductController::kitList'], [], [['text', '/kits']], [], []],
    'pizzaAdd' => [['id'], ['_controller' => 'App\\Controller\\ProductController::kitAddPizza'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/pizzas/addingPizza']], [], []],
    'removePizza' => [['id'], ['_controller' => 'App\\Controller\\ProductController::kitRemovePizza'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/kits/removePizza']], [], []],
    'drinkAdd' => [['id'], ['_controller' => 'App\\Controller\\ProductController::kitAddDrink'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/drinks/addingDrink']], [], []],
    'removeDrink' => [['id'], ['_controller' => 'App\\Controller\\ProductController::kitRemoveDrink'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/kits/removeDrink']], [], []],
    'rollAdd' => [['id'], ['_controller' => 'App\\Controller\\ProductController::kitAddRoll'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/rolls/addingRolls']], [], []],
    'removeRoll' => [['id'], ['_controller' => 'App\\Controller\\ProductController::kitRemoveRoll'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/kits/removeRoll']], [], []],
    'order' => [[], ['_controller' => 'App\\Controller\\ProductController::createOrder'], [], [['text', '/order']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
