<?php

namespace ContainerScqsUcx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W7gVUmkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.W7gVUmk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.W7gVUmk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'kitRepository' => ['privates', 'App\\Repository\\DeliveryKitRepository', 'getDeliveryKitRepositoryService', true],
        ], [
            'kitRepository' => 'App\\Repository\\DeliveryKitRepository',
        ]);
    }
}
