<?php

namespace ContainerScqsUcx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IyCh3jLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iyCh3jL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iyCh3jL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'deliveryRoll' => ['privates', '.errored..service_locator.iyCh3jL.App\\Entity\\DeliveryRoll', NULL, 'Cannot autowire service ".service_locator.iyCh3jL": it references class "App\\Entity\\DeliveryRoll" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'deliveryRoll' => 'App\\Entity\\DeliveryRoll',
            'entityManager' => '?',
        ]);
    }
}
