<?php

namespace ContainerScqsUcx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Uhclp5LService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Uhclp5L' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Uhclp5L'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rollRepository' => ['privates', 'App\\Repository\\DeliveryRollRepository', 'getDeliveryRollRepositoryService', true],
        ], [
            'rollRepository' => 'App\\Repository\\DeliveryRollRepository',
        ]);
    }
}
