<?php

namespace ContainerScqsUcx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeliveryRollService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.iyCh3jL.App\Entity\DeliveryRoll' shared service.
     *
     * @return \App\Entity\DeliveryRoll
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.iyCh3jL": it references class "App\\Entity\\DeliveryRoll" but no such service exists.');
    }
}
