<?php

namespace ContainerR32S4wb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3hLVgvHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3hLVgvH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3hLVgvH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'drinkRepository' => ['privates', 'App\\Repository\\DeliveryDrinkRepository', 'getDeliveryDrinkRepositoryService', true],
        ], [
            'drinkRepository' => 'App\\Repository\\DeliveryDrinkRepository',
        ]);
    }
}
