<?php

namespace ContainerR32S4wb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OhQ5cxKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OhQ5cxK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OhQ5cxK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ProductController::createOrder' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\ProductController::drinkList' => ['privates', '.service_locator.3hLVgvH', 'get_ServiceLocator_3hLVgvHService', true],
            'App\\Controller\\ProductController::kitAddDrink' => ['privates', '.service_locator.DxXZuyj', 'get_ServiceLocator_DxXZuyjService', true],
            'App\\Controller\\ProductController::kitAddPizza' => ['privates', '.service_locator.iLXbvph', 'get_ServiceLocator_ILXbvphService', true],
            'App\\Controller\\ProductController::kitAddRoll' => ['privates', '.service_locator.iyCh3jL', 'get_ServiceLocator_IyCh3jLService', true],
            'App\\Controller\\ProductController::kitList' => ['privates', '.service_locator.W7gVUmk', 'get_ServiceLocator_W7gVUmkService', true],
            'App\\Controller\\ProductController::kitRemoveDrink' => ['privates', '.service_locator.z4j5Y9z', 'get_ServiceLocator_Z4j5Y9zService', true],
            'App\\Controller\\ProductController::kitRemovePizza' => ['privates', '.service_locator.z4j5Y9z', 'get_ServiceLocator_Z4j5Y9zService', true],
            'App\\Controller\\ProductController::kitRemoveRoll' => ['privates', '.service_locator.z4j5Y9z', 'get_ServiceLocator_Z4j5Y9zService', true],
            'App\\Controller\\ProductController::pizzaList' => ['privates', '.service_locator.4eV2O7n', 'get_ServiceLocator_4eV2O7nService', true],
            'App\\Controller\\ProductController::rollList' => ['privates', '.service_locator.Uhclp5L', 'get_ServiceLocator_Uhclp5LService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\ProductController:createOrder' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\ProductController:drinkList' => ['privates', '.service_locator.3hLVgvH', 'get_ServiceLocator_3hLVgvHService', true],
            'App\\Controller\\ProductController:kitAddDrink' => ['privates', '.service_locator.DxXZuyj', 'get_ServiceLocator_DxXZuyjService', true],
            'App\\Controller\\ProductController:kitAddPizza' => ['privates', '.service_locator.iLXbvph', 'get_ServiceLocator_ILXbvphService', true],
            'App\\Controller\\ProductController:kitAddRoll' => ['privates', '.service_locator.iyCh3jL', 'get_ServiceLocator_IyCh3jLService', true],
            'App\\Controller\\ProductController:kitList' => ['privates', '.service_locator.W7gVUmk', 'get_ServiceLocator_W7gVUmkService', true],
            'App\\Controller\\ProductController:kitRemoveDrink' => ['privates', '.service_locator.z4j5Y9z', 'get_ServiceLocator_Z4j5Y9zService', true],
            'App\\Controller\\ProductController:kitRemovePizza' => ['privates', '.service_locator.z4j5Y9z', 'get_ServiceLocator_Z4j5Y9zService', true],
            'App\\Controller\\ProductController:kitRemoveRoll' => ['privates', '.service_locator.z4j5Y9z', 'get_ServiceLocator_Z4j5Y9zService', true],
            'App\\Controller\\ProductController:pizzaList' => ['privates', '.service_locator.4eV2O7n', 'get_ServiceLocator_4eV2O7nService', true],
            'App\\Controller\\ProductController:rollList' => ['privates', '.service_locator.Uhclp5L', 'get_ServiceLocator_Uhclp5LService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\ProductController::createOrder' => '?',
            'App\\Controller\\ProductController::drinkList' => '?',
            'App\\Controller\\ProductController::kitAddDrink' => '?',
            'App\\Controller\\ProductController::kitAddPizza' => '?',
            'App\\Controller\\ProductController::kitAddRoll' => '?',
            'App\\Controller\\ProductController::kitList' => '?',
            'App\\Controller\\ProductController::kitRemoveDrink' => '?',
            'App\\Controller\\ProductController::kitRemovePizza' => '?',
            'App\\Controller\\ProductController::kitRemoveRoll' => '?',
            'App\\Controller\\ProductController::pizzaList' => '?',
            'App\\Controller\\ProductController::rollList' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ProductController:createOrder' => '?',
            'App\\Controller\\ProductController:drinkList' => '?',
            'App\\Controller\\ProductController:kitAddDrink' => '?',
            'App\\Controller\\ProductController:kitAddPizza' => '?',
            'App\\Controller\\ProductController:kitAddRoll' => '?',
            'App\\Controller\\ProductController:kitList' => '?',
            'App\\Controller\\ProductController:kitRemoveDrink' => '?',
            'App\\Controller\\ProductController:kitRemovePizza' => '?',
            'App\\Controller\\ProductController:kitRemoveRoll' => '?',
            'App\\Controller\\ProductController:pizzaList' => '?',
            'App\\Controller\\ProductController:rollList' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
