<?php

namespace ContainerR32S4wb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z4j5Y9zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z4j5Y9z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z4j5Y9z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'deliveryKit' => ['privates', '.errored..service_locator.z4j5Y9z.App\\Entity\\DeliveryKit', NULL, 'Cannot autowire service ".service_locator.z4j5Y9z": it references class "App\\Entity\\DeliveryKit" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'kitRepository' => ['privates', 'App\\Repository\\DeliveryKitRepository', 'getDeliveryKitRepositoryService', true],
        ], [
            'deliveryKit' => 'App\\Entity\\DeliveryKit',
            'entityManager' => '?',
            'kitRepository' => 'App\\Repository\\DeliveryKitRepository',
        ]);
    }
}
