<?php

namespace ContainerR32S4wb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ILXbvphService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iLXbvph' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iLXbvph'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'deliveryPizza' => ['privates', '.errored..service_locator.iLXbvph.App\\Entity\\DeliveryPizza', NULL, 'Cannot autowire service ".service_locator.iLXbvph": it references class "App\\Entity\\DeliveryPizza" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'deliveryPizza' => 'App\\Entity\\DeliveryPizza',
            'entityManager' => '?',
        ]);
    }
}
