<?php

namespace ContainerR32S4wb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeliveryDrinkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DxXZuyj.App\Entity\DeliveryDrink' shared service.
     *
     * @return \App\Entity\DeliveryDrink
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.DxXZuyj": it references class "App\\Entity\\DeliveryDrink" but no such service exists.');
    }
}
