<?php

namespace ContainerR32S4wb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeliveryPizzaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.iLXbvph.App\Entity\DeliveryPizza' shared service.
     *
     * @return \App\Entity\DeliveryPizza
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.iLXbvph": it references class "App\\Entity\\DeliveryPizza" but no such service exists.');
    }
}
